apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-finalizer"
  namespace: {{ .Values.installation.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-failed
spec:
  backoffLimit: 0
  template:
    metadata:
      name: "{{ .Release.Name }}-finalizer"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      serviceAccountName: kruise-manager
      containers:
        - name: pre-delete-job
          image: "openkruise/kruise-helm-hook"
          imagePullPolicy: IfNotPresent